services:
  app1:
    container_name: app1
    build: .
    env_file:
      - .env
    environment:
      - APP_NAME=APP1
    volumes:
      - .:/app
      - /app/node_modules
  app2:
    container_name: app2
    build: .
    env_file:
      - .env
    environment:
      - APP_NAME=APP2
    volumes:
      - ./src:/app/src
      - /app/node_modules
  app3:
    container_name: app3
    build: .
    env_file:
      - .env
    environment:
      - APP_NAME=APP3
    volumes:
      - .:/app
      - /app/node_modules
  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.20-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
